import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';
const html = fs.readFileSync(new URL('../../frontend/app/admin.html',import.meta.url),'utf8');
const source = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].at(-1)[1];
const fixtureSource = fs.readFileSync(new URL('./admin_member_fixture.js',import.meta.url),'utf8');
const settle = () => new Promise(resolve=>setTimeout(resolve,5));
async function setup(options={}) {
 const dom=new JSDOM(html,{url:'http://127.0.0.1:8765/admin.html',runScripts:'outside-only'});
 const w=dom.window; w.HTMLElement.prototype.scrollIntoView=function(){};
 w.eval(fixtureSource);w.installAdminFixture(options);w.eval(source);await settle();
 return {dom,w,d:w.document,f:w.fixture};
}
let checks=0;
const check=(label,fn)=>{fn();checks++;console.log(`PASS ${label}`);};
const {dom,w,d,f}=await setup();
const click=async selector=>{const node=d.querySelector(selector);assert.ok(node,selector);node.click();await settle();};
const tab=key=>click(`#member-tab-${key}`);
check('selected identity, backend-approved email not in old frontend allowlist',()=>assert.match(d.querySelector('#detail-header').textContent,/Mei Lin/));
check('exactly five tabs and speaking default',()=>{assert.deepEqual([...d.querySelectorAll('#detail-subtabs button')].map(b=>b.textContent),['口說','寫作','閱讀','訂閱管理','AI 生成報告']);assert.ok(d.querySelector('#sub-speaking.active'));});
check('initial fetches only member list and ten speaking records',()=>{assert.equal(f.requests.length,2);assert.match(f.requests[1].query,/limit=10/);assert.equal(d.querySelectorAll('#middle-content .prow').length,10);assert.match(d.querySelector('.weakness-summary').textContent,/缺少具體細節 37/);});
await click('#speaking-next');check('speaking server pagination',()=>{assert.match(f.requests.at(-1).query,/offset=10/);assert.match(d.querySelector('.member-pagination').textContent,/11–20/);});
await click('#middle-content .prow');check('speaking transcript and coaching detail retained',()=>assert.match(d.querySelector('#record-detail-content').textContent,/Use a specific example/));
await tab('writing');await click('#sub-writing .lrow');check('writing list and essay feedback',()=>{assert.equal(d.querySelectorAll('#sub-writing .lrow').length,4);assert.match(d.querySelector('#sw0').textContent,/Make the overview clearer/);assert.equal(d.querySelector('#sw0').hidden,false);});
await tab('reading');check('reading compact list and truthful metrics',()=>{assert.equal(d.querySelectorAll('#sub-reading .lrow').length,10);assert.match(d.querySelector('#sub-reading').textContent,/平均正確率 80%/);});
const before=f.requests.length;await tab('writing');await tab('reading');check('cached tab reopen does not fetch',()=>assert.equal(f.requests.length,before));
await tab('subscription');check('all management actions inside subscription panel',()=>{assert.equal(d.querySelector('#subs-revoke-btn').closest('.subpanel').id,'sub-subscription');assert.equal(d.querySelector('[data-extend]').closest('.subpanel').id,'sub-subscription');assert.match(d.querySelector('#sub-subscription').textContent,/subscription \+ grant/);assert.equal(d.querySelectorAll('#detail-header button').length,0);});
await tab('ai');check('AI tab does not auto-generate and preserves two actions',()=>{assert.equal(f.requests.filter(r=>r.path.includes('diagnosis')||r.path.includes('student_brief')).length,0);assert.equal(d.querySelector('#brief-btn').closest('.subpanel').id,'sub-ai');assert.ok(d.querySelector('#diag-btn'));});
await click('#diag-btn');check('manual diagnosis output and generated timestamp',()=>assert.match(d.querySelector('#diag-content').textContent,/生成時間.*2026/));
const releaseBrief=f.hold('/student_brief/');await click('#brief-btn');
await click(`[data-user-id="${f.other}"]`);releaseBrief();await settle();
check('switching member clears panels, resets default and isolates in-flight report',()=>{assert.match(d.querySelector('#detail-header').textContent,/Alex Chen/);assert.ok(d.querySelector('#sub-speaking.active'));assert.equal(d.querySelector('#brief-content').textContent,'');assert.match(d.querySelector('#middle-content').textContent,/沒有口說紀錄/);});
await tab('writing');check('writing empty state',()=>assert.match(d.querySelector('#sub-writing').textContent,/尚未提交寫作/));
f.failures.set('/admin/reading/attempts',503);await tab('reading');check('partial failure visible',()=>assert.match(d.querySelector('#sub-reading').textContent,/載入失敗/));
await tab('subscription');check('subscription remains usable after reading failure',()=>assert.ok(d.querySelector('#subs-upgrade-trigger')));
await click('#subs-upgrade-trigger');await click('#subs-grant-btn');check('grant reason required',()=>assert.match(d.querySelector('#subs-pro-result').textContent,/Reason is required/));
d.querySelector('#subs-reason-input').value='test only';await click('[data-expiry="7"]');await click('#subs-grant-btn');check('grant uses captured member, expiry and refreshes badge',()=>{const req=f.requests.find(r=>r.path.endsWith('/pro_grant'));assert.match(req.path,new RegExp(f.other));assert.ok(req.body.expires_at);assert.match(d.querySelector('#detail-header').textContent,/PRO/);});
const mutations=()=>f.requests.filter(r=>r.method==='PATCH').length;
w.confirm=()=>false;const n=mutations();await click('#subs-revoke-btn');check('revoke confirmation cancel prevents mutation',()=>assert.equal(mutations(),n));
f.failures.clear();await tab('reading');check('failed tab retries and renders empty',()=>assert.match(d.querySelector('#sub-reading').textContent,/尚無閱讀紀錄/));
const releaseSpeaking=f.hold(`/admin/user/${f.uid}`);await click(`[data-user-id="${f.uid}"]`);await click(`[data-user-id="${f.other}"]`);releaseSpeaking();await settle();check('late speaking response cannot overwrite selected member',()=>assert.match(d.querySelector('#middle-content').textContent,/0 次/));
d.querySelector('#user-search').value='Mei';d.querySelector('#user-search').dispatchEvent(new w.Event('input'));check('name search',()=>assert.equal(d.querySelectorAll('#users-list .user-row').length,1));
d.querySelector('#user-search').value='';d.querySelector('#user-search').dispatchEvent(new w.Event('input'));await click('#user-chips [data-filter="free"]');check('FREE filter',()=>assert.ok([...d.querySelectorAll('#users-list .user-row')].every(row=>row.textContent.includes('FREE'))));
const first=d.querySelector('#member-tab-speaking');first.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));await settle();check('keyboard tab switch',()=>assert.ok(d.querySelector('#sub-writing.active')));
check('no hardcoded admin authorization array',()=>assert.doesNotMatch(source,/ADMIN_EMAILS|galant19951209/));
dom.window.close();
const denied=await setup({denied:true});check('server 403 closes admin surface',()=>{assert.match(denied.d.body.textContent,/無法存取管理介面/);assert.equal(denied.f.requests.length,1);assert.equal(denied.d.querySelector('#detail-pane'),null);});denied.dom.window.close();
console.log(`Admin member DOM harness: ${checks} checks passed`);
